import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import RecoilProvider from "./recoilProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MeetingApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={inter.className}>
        <RecoilProvider>
          <main className="min-h-screen p-10">{children}</main>
          <Toaster />
        </RecoilProvider>
      </body>
    </html>
  );
}
